# Generated by Django 3.1.1 on 2021-01-15 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifesaver', '0002_patient_department3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='department1',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='nurse',
            old_name='department2',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='department3',
            new_name='department',
        ),
    ]
