# Generated by Django 3.1.1 on 2021-01-15 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifesaver', '0004_auto_20210115_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='workshift',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='lifesaver.workshift'),
        ),
    ]
