# Generated by Django 3.1.1 on 2021-01-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifesaver', '0005_nurse_workshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshift',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
