# Generated by Django 3.1.1 on 2021-01-15 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifesaver', '0008_remove_nurse_workshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='work_shift',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='lifesaver.workshift'),
        ),
    ]
