# Generated by Django 3.1.1 on 2021-01-16 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifesaver', '0009_nurse_work_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='work_shift',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='lifesaver.workshift'),
        ),
    ]
