# Generated by Django 3.1.1 on 2021-01-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifesaver', '0010_auto_20210116_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse',
            name='work_shift',
        ),
        migrations.AddField(
            model_name='nurse',
            name='end_datetime',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='start_datetime',
            field=models.DateField(blank=True, null=True),
        ),
    ]
