# Generated by Django 3.1.5 on 2021-01-16 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifesaver', '0015_auto_20210116_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='work_shift',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lifesaver.workshift'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lifesaver.department'),
        ),
    ]
